###
#POST создать пост
POST http://127.0.0.1/api/users/
Content-Type: application/json

{
"username": "win",
"email": "win@win.ru",
"first_name": "win",
"password":"win090909"
}

###
GET http://localhost/api/recipes/
Content-Type: application/json
Authorization: Token  d532a0c283cc6db6d0c9c63232ea0c9b1382b0ed

###
POST http://localhost/api/recipes/
Content-Type: application/json
Authorization: Token  198111e4dababfec073316634600e6ff49ede9a7

{
  "ingredients": [
    {
      "id": 1890,
      "amount": 10
    },
    {
      "id": 2109,
      "amount": 10
    }
  ],

  "tags": [
    3
  ],
  "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
  "name": "kkh",
  "text": "string",
  "cooking_time": 10
}


###
POST  http://localhost/api/recipes/
Content-Type: application/json
Authorization: Token  d532a0c283cc6db6d0c9c63232ea0c9b1382b0ed

{
  "ingredients": [
    {
      "id": 100,
      "amount" :16
    },
    {
      "id": 170,
      "amount" :9
    }
  ]
}
###
#POST создать пост
POST  http://localhost/api/auth/token/login/
Content-Type: application/json

{
"email": "pin@pin.ru",
"password":"pin"
}
###
#POST создать пост
POST  http://localhost/api/auth/token/login/
Content-Type: application/json

{
"email": "kin@kin.ru",
"password":"kin"
}

###
#POST создать пост
POST  http://localhost/api/auth/token/login/
Content-Type: application/json

{
"email": "iop@iop.ru",
"password":"iop"
}
###
#POST создать пост
POST http://127.0.0.1:8000/api/auth/token/login/
Content-Type: application/json

{
"username": "alena",
"password": "alena090909"
}

###
GET  http://127.0.0.1/api/users/me/
Content-Type: application/json
Authorization: Token edebca6ee74a85e46e738b5d8558f89022143799
###
GET  http://127.0.0.1/api/recipes/
Content-Type: application/json
Authorization: Token 198111e4dababfec073316634600e6ff49ede9a7

###
POST  http://127.0.0.1:8000/api/users/set_password/
Content-Type: application/json
Authorization: Token 0b9f60964505f9e61c7ffc864bfdfbdabb4eac53

{
"new_password": "pirog09090909",
"current_password": "pirog090909"
}

###
POST http://127.0.0.1:8000/api/auth/token/logout/
Content-Type: application/json
Authorization: Token e4dedfbb43adf5f0e3bbda27e72b56047b8189fb

###
GET http://localhost/api/tags/
Content-Type: application/json
#Authorization: Token  6eae872cc5df08b064b916c3076b17d6fecea7a8

###
GET http://localhost/api/ingredients/1001/
Content-Type: application/json
Authorization: Token  198111e4dababfec073316634600e6ff49ede9a7

###
POST http://localhost/api/recipes/125/favorite/
Authorization: Token  198111e4dababfec073316634600e6ff49ede9a7
###
#http://foodgram.example.org/api/users/?page=4
GET http://localhost/api/recipes/?author=2
Content-Type: application/json
#Authorization: Token  198111e4dababfec073316634600e6ff49ede9a7

###
POST http://localhost/api/users/2/subscribe/
#Authorization: Token  24f30db4396c578094e4e6a6b4dcb29b97d414bc
###
GET  http://localhost/api/users/subscriptions/
Authorization: Token 24f30db4396c578094e4e6a6b4dcb29b97d414bc
###

###
GET   http://localhost/api/users/me/
Authorization: Token  198111e4dababfec073316634600e6ff49ede9a7
###
GET   http://localhost/api/users/subscriptions/
Authorization: Token  d532a0c283cc6db6d0c9c63232ea0c9b1382b0ed

###
GET  http://localhost/api/users/?is_in_shopping_cart=1
Authorization: Token  198111e4dababfec073316634600e6ff49ede9a7

###
GET http://localhost/api/recipes/?is_in_shopping_cart=1&is_favorited=1
Authorization: Token  198111e4dababfec073316634600e6ff49ede9a7

###
GET  http://localhost/api/recipes/download_shopping_cart
Authorization: Token  198111e4dababfec073316634600e6ff49ede9a7