# Generated by Django 3.2.17 on 2023-02-13 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230213_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(1)]),
        ),
    ]
