# Generated by Django 3.2.17 on 2023-02-14 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_favorite_user_to_recipe_favorite'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='user_to_recipe_favorite',
        ),
    ]
