# Generated by Django 3.2.17 on 2023-02-16 02:01

import django.core.validators
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20230215_2303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(
                fields=('user', 'author'), name='user_to_author_follow'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(
                check=models.Q(
                    ('author',
                     django.db.models.expressions.F('user')),
                    _negated=True),
                name='following_himself'),
        ),
    ]
